In [1]:
import os
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import sklearn

In [2]:
df=pd.read_csv('medical_disease.csv')   # read medical_disease.csv file and store in dataframe df

In [3]:
df

,Age,Gender,BMI,BloodPressure,GlucoseLevel,Cholesterol,HeartRate,Smoking,Alcohol,PhysicalActivity,FamilyHistory,Disease
0,23,Male,17.5,102,177,161,88,No,No,Medium,No,Healthy
1,69,Male,31.1,118,256,147,92,No,No,High,Yes,Pre-Diabetes
2,61,Female,31.3,114,206,193,74,Yes,No,Medium,No,Healthy
3,47,Female,23.9,105,162,253,68,No,No,Low,No,Healthy
4,47,Male,28.3,148,121,280,84,No,Yes,High,No,Healthy
...,...,...,...,...,...,...,...,...,...,...,...,...
9995,49,Male,27.1,177,183,268,59,No,No,High,No,Hypertension
9996,84,Male,29.2,142,215,145,77,No,Yes,High,Yes,Hypertension
9997,41,Male,22.8,177,265,133,71,No,No,Medium,Yes,Hypertension
9998,55,Male,29.0,126,241,298,57,No,No,Medium,Yes,Pre-Diabetes
9999,59,Male,32.2,151,162,225,93,No,No,High,Yes,Pre-Diabetes

In [4]:
print("duplicate values : ",df.duplicated().sum())
print("null values : ",df.isnull().sum())

duplicate values :  0
null values :  Age                 0
Gender              0
BMI                 0
BloodPressure       0
GlucoseLevel        0
Cholesterol         0
HeartRate           0
Smoking             0
Alcohol             0
PhysicalActivity    0
FamilyHistory       0
Disease             0
dtype: int64

In [5]:
df['Gender'].unique()

<StringArray>
['Male', 'Female']
Length: 2, dtype: str

In [6]:
df['Gender']=df['Gender'].map({'Male':1,'Female':0}) # map the values

In [7]:
df['Smoking'].unique()

<StringArray>
['No', 'Yes']
Length: 2, dtype: str

In [8]:
df['Smoking'] = df['Smoking'].str.strip().str.title().map({'No':0, 'Yes':1}) # map the values of Smoking column to 0 and 1 and also remove any leading or trailing spaces and convert to title case

In [9]:
df['Alcohol'].unique()

<StringArray>
['No', 'Yes']
Length: 2, dtype: str

In [10]:
df['Alcohol'] = df['Alcohol'].str.strip().str.title().map({'No':0, 'Yes':1})

In [11]:
df['PhysicalActivity'].unique()

<StringArray>
['Medium', 'High', 'Low']
Length: 3, dtype: str

In [12]:
df['PhysicalActivity']=df['PhysicalActivity'].str.strip().str.title().map({'Medium':2,'High':3,'Low':1})

In [13]:
df['FamilyHistory'].unique()

<StringArray>
['No', 'Yes']
Length: 2, dtype: str

In [14]:
df['FamilyHistory']=df['FamilyHistory'].str.strip().str.title().map({'No':0,'Yes':1})

In [15]:
df['Disease'].unique()

<StringArray>
['Healthy', 'Pre-Diabetes', 'Hypertension', 'Heart Disease', 'Diabetes']
Length: 5, dtype: str

In [16]:
df['Disease']=df['Disease'].str.strip().str.title().map({'Healthy':0,'Pre-Diabetes':1,'Hypertension':2,'Heart Disease':3,'Diabetes':4})

In [17]:
df

,Age,Gender,BMI,BloodPressure,GlucoseLevel,Cholesterol,HeartRate,Smoking,Alcohol,PhysicalActivity,FamilyHistory,Disease
0,23,1,17.5,102,177,161,88,0,0,2,0,0
1,69,1,31.1,118,256,147,92,0,0,3,1,1
2,61,0,31.3,114,206,193,74,1,0,2,0,0
3,47,0,23.9,105,162,253,68,0,0,1,0,0
4,47,1,28.3,148,121,280,84,0,1,3,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...
9995,49,1,27.1,177,183,268,59,0,0,3,0,2
9996,84,1,29.2,142,215,145,77,0,1,3,1,2
9997,41,1,22.8,177,265,133,71,0,0,2,1,2
9998,55,1,29.0,126,241,298,57,0,0,2,1,1
9999,59,1,32.2,151,162,225,93,0,0,3,1,1

In [18]:
x=df.drop('Disease',axis=1)

In [19]:
x

,Age,Gender,BMI,BloodPressure,GlucoseLevel,Cholesterol,HeartRate,Smoking,Alcohol,PhysicalActivity,FamilyHistory
0,23,1,17.5,102,177,161,88,0,0,2,0
1,69,1,31.1,118,256,147,92,0,0,3,1
2,61,0,31.3,114,206,193,74,1,0,2,0
3,47,0,23.9,105,162,253,68,0,0,1,0
4,47,1,28.3,148,121,280,84,0,1,3,0
...,...,...,...,...,...,...,...,...,...,...,...
9995,49,1,27.1,177,183,268,59,0,0,3,0
9996,84,1,29.2,142,215,145,77,0,1,3,1
9997,41,1,22.8,177,265,133,71,0,0,2,1
9998,55,1,29.0,126,241,298,57,0,0,2,1
9999,59,1,32.2,151,162,225,93,0,0,3,1

In [20]:
y=df[['Disease']]

In [21]:
y

      Disease
0           0
1           1
2           0
3           0
4           0
...       ...
9995        2
9996        2
9997        2
9998        1
9999        1

[10000 rows x 1 columns]

#### svm