In [1]:
import os
import numpy as np
import pandas as pd

In [2]:
df=pd.read_csv('medical_disease.csv')   # read medical_disease.csv file and store in dataframe df

In [3]:
df

,Age,Gender,BMI,BloodPressure,GlucoseLevel,Cholesterol,HeartRate,Smoking,Alcohol,PhysicalActivity,FamilyHistory,Disease
0,23,Male,17.5,102,177,161,88,No,No,Medium,No,Healthy
1,69,Male,31.1,118,256,147,92,No,No,High,Yes,Pre-Diabetes
2,61,Female,31.3,114,206,193,74,Yes,No,Medium,No,Healthy
3,47,Female,23.9,105,162,253,68,No,No,Low,No,Healthy
4,47,Male,28.3,148,121,280,84,No,Yes,High,No,Healthy
...,...,...,...,...,...,...,...,...,...,...,...,...
9995,49,Male,27.1,177,183,268,59,No,No,High,No,Hypertension
9996,84,Male,29.2,142,215,145,77,No,Yes,High,Yes,Hypertension
9997,41,Male,22.8,177,265,133,71,No,No,Medium,Yes,Hypertension
9998,55,Male,29.0,126,241,298,57,No,No,Medium,Yes,Pre-Diabetes
9999,59,Male,32.2,151,162,225,93,No,No,High,Yes,Pre-Diabetes

In [4]:
df['Gender']=df['Gender'].map({'Male':1,'Female':0}) # map the values

In [5]:
df['Gender'].unique() # check the unique values in gender column

array([1, 0])

In [6]:
df

,Age,Gender,BMI,BloodPressure,GlucoseLevel,Cholesterol,HeartRate,Smoking,Alcohol,PhysicalActivity,FamilyHistory,Disease
0,23,1,17.5,102,177,161,88,No,No,Medium,No,Healthy
1,69,1,31.1,118,256,147,92,No,No,High,Yes,Pre-Diabetes
2,61,0,31.3,114,206,193,74,Yes,No,Medium,No,Healthy
3,47,0,23.9,105,162,253,68,No,No,Low,No,Healthy
4,47,1,28.3,148,121,280,84,No,Yes,High,No,Healthy
...,...,...,...,...,...,...,...,...,...,...,...,...
9995,49,1,27.1,177,183,268,59,No,No,High,No,Hypertension
9996,84,1,29.2,142,215,145,77,No,Yes,High,Yes,Hypertension
9997,41,1,22.8,177,265,133,71,No,No,Medium,Yes,Hypertension
9998,55,1,29.0,126,241,298,57,No,No,Medium,Yes,Pre-Diabetes
9999,59,1,32.2,151,162,225,93,No,No,High,Yes,Pre-Diabetes

In [7]:
df['Smoking'] = df['Smoking'].str.strip().str.title().map({'No':0, 'Yes':1}) # map the values of Smoking column to 0 and 1
#and also remove any leading or trailing spaces and convert to title case

In [8]:
df

,Age,Gender,BMI,BloodPressure,GlucoseLevel,Cholesterol,HeartRate,Smoking,Alcohol,PhysicalActivity,FamilyHistory,Disease
0,23,1,17.5,102,177,161,88,0,No,Medium,No,Healthy
1,69,1,31.1,118,256,147,92,0,No,High,Yes,Pre-Diabetes
2,61,0,31.3,114,206,193,74,1,No,Medium,No,Healthy
3,47,0,23.9,105,162,253,68,0,No,Low,No,Healthy
4,47,1,28.3,148,121,280,84,0,Yes,High,No,Healthy
...,...,...,...,...,...,...,...,...,...,...,...,...
9995,49,1,27.1,177,183,268,59,0,No,High,No,Hypertension
9996,84,1,29.2,142,215,145,77,0,Yes,High,Yes,Hypertension
9997,41,1,22.8,177,265,133,71,0,No,Medium,Yes,Hypertension
9998,55,1,29.0,126,241,298,57,0,No,Medium,Yes,Pre-Diabetes
9999,59,1,32.2,151,162,225,93,0,No,High,Yes,Pre-Diabetes