In [61]:
import pandas as pd
import numpy as np

In [62]:
student_dict={
    'name': ['Rehan', 'mukesh', 'saloni', 'riya', 'saloni'],
    'marks': [90, 80, 70, 60, 50],
    'branch': ['CSE', 'CSE', 'CSE', 'CSE', 'CSE']
}

In [63]:
df=pd.DataFrame(student_dict)
df

     name  marks branch
0   Rehan     90    CSE
1  mukesh     80    CSE
2  saloni     70    CSE
3    riya     60    CSE
4  saloni     50    CSE

In [64]:
df=pd.read_csv('medical_disease.csv')

In [65]:
char_df=df.select_dtypes(include='object')  # Select only the character columns from the DataFrame

C:\Users\rehan\AppData\Local\Temp\ipykernel_18412\2898323532.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  char_df=df.select_dtypes(include='object')  # Select only the character columns from the DataFrame

In [66]:
char_df  # Display the character DataFrame

      Gender Smoking Alcohol PhysicalActivity FamilyHistory       Disease
0       Male      No      No           Medium            No       Healthy
1       Male      No      No             High           Yes  Pre-Diabetes
2     Female     Yes      No           Medium            No       Healthy
3     Female      No      No              Low            No       Healthy
4       Male      No     Yes             High            No       Healthy
...      ...     ...     ...              ...           ...           ...
9995    Male      No      No             High            No  Hypertension
9996    Male      No     Yes             High           Yes  Hypertension
9997    Male      No      No           Medium           Yes  Hypertension
9998    Male      No      No           Medium           Yes  Pre-Diabetes
9999    Male      No      No             High           Yes  Pre-Diabetes

[10000 rows x 6 columns]

In [67]:
df

,Age,Gender,BMI,BloodPressure,GlucoseLevel,Cholesterol,HeartRate,Smoking,Alcohol,PhysicalActivity,FamilyHistory,Disease
0,23,Male,17.5,102,177,161,88,No,No,Medium,No,Healthy
1,69,Male,31.1,118,256,147,92,No,No,High,Yes,Pre-Diabetes
2,61,Female,31.3,114,206,193,74,Yes,No,Medium,No,Healthy
3,47,Female,23.9,105,162,253,68,No,No,Low,No,Healthy
4,47,Male,28.3,148,121,280,84,No,Yes,High,No,Healthy
...,...,...,...,...,...,...,...,...,...,...,...,...
9995,49,Male,27.1,177,183,268,59,No,No,High,No,Hypertension
9996,84,Male,29.2,142,215,145,77,No,Yes,High,Yes,Hypertension
9997,41,Male,22.8,177,265,133,71,No,No,Medium,Yes,Hypertension
9998,55,Male,29.0,126,241,298,57,No,No,Medium,Yes,Pre-Diabetes
9999,59,Male,32.2,151,162,225,93,No,No,High,Yes,Pre-Diabetes

In [68]:
total_df=pd.concat([char_df, df], axis=1)  # Concatenate the character DataFrame and the original DataFrame along columns

In [69]:
total_df

,Gender,Smoking,Alcohol,PhysicalActivity,FamilyHistory,Disease,Age,Gender,BMI,BloodPressure,GlucoseLevel,Cholesterol,HeartRate,Smoking,Alcohol,PhysicalActivity,FamilyHistory,Disease
0,Male,No,No,Medium,No,Healthy,23,Male,17.5,102,177,161,88,No,No,Medium,No,Healthy
1,Male,No,No,High,Yes,Pre-Diabetes,69,Male,31.1,118,256,147,92,No,No,High,Yes,Pre-Diabetes
2,Female,Yes,No,Medium,No,Healthy,61,Female,31.3,114,206,193,74,Yes,No,Medium,No,Healthy
3,Female,No,No,Low,No,Healthy,47,Female,23.9,105,162,253,68,No,No,Low,No,Healthy
4,Male,No,Yes,High,No,Healthy,47,Male,28.3,148,121,280,84,No,Yes,High,No,Healthy
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,Male,No,No,High,No,Hypertension,49,Male,27.1,177,183,268,59,No,No,High,No,Hypertension
9996,Male,No,Yes,High,Yes,Hypertension,84,Male,29.2,142,215,145,77,No,Yes,High,Yes,Hypertension
9997,Male,No,No,Medium,Yes,Hypertension,41,Male,22.8,177,265,133,71,No,No,Medium,Yes,Hypertension
9998,Male,No,No,Medium,Yes,Pre-Diabetes,55,Male,29.0,126,241,298,57,No,No,Medium,Yes,Pre-Diabetes
9999,Male,No,No,High,Yes,Pre-Diabetes,59,Male,32.2,151,162,225,93,No,No,High,Yes,Pre-Diabetes

In [70]:
num_df=df.select_dtypes(exclude='object')  # Select only the numeric columns from the DataFrame

In [71]:
num_df

      Age   BMI  BloodPressure  GlucoseLevel  Cholesterol  HeartRate
0      23  17.5            102           177          161         88
1      69  31.1            118           256          147         92
2      61  31.3            114           206          193         74
3      47  23.9            105           162          253         68
4      47  28.3            148           121          280         84
...   ...   ...            ...           ...          ...        ...
9995   49  27.1            177           183          268         59
9996   84  29.2            142           215          145         77
9997   41  22.8            177           265          133         71
9998   55  29.0            126           241          298         57
9999   59  32.2            151           162          225         93

[10000 rows x 6 columns]

In [72]:
df.groupby('Disease') # Group the DataFrame by the 'Disease' column

In [73]:
Disease=df.groupby('Disease')["BMI"].sum()

In [74]:
Disease

Disease
Diabetes           6248.1
Healthy          161156.1
Heart Disease      6745.3
Hypertension      47795.1
Pre-Diabetes      38875.4
Name: BMI, dtype: float64

In [75]:
Disease=df.groupby('Disease')["BMI"].count()

In [81]:
Disease

Disease
Diabetes          215
Healthy          6329
Heart Disease     232
Hypertension     1771
Pre-Diabetes     1453
Name: BMI, dtype: int64

In [76]:
import pandas as pd

data = {
    'Department': ['HR', 'IT', 'HR', 'IT', 'Sales'],
    'Employee': ['Alice', 'Bob', 'Charlie', 'David', 'Eva'],
    'Salary': [50000, 70000, 60000, 80000, 55000]
}
df=pd.DataFrame(data)

In [77]:
df

  Department Employee  Salary
0         HR    Alice   50000
1         IT      Bob   70000
2         HR  Charlie   60000
3         IT    David   80000
4      Sales      Eva   55000

In [78]:
df.groupby('Employee')

In [79]:
df.groupby('Department')["Salary"].sum()

Department
HR       110000
IT       150000
Sales     55000
Name: Salary, dtype: int64

In [80]:
df.groupby('Department')["Employee"].count()

Department
HR       2
IT       2
Sales    1
Name: Employee, dtype: int64